name: cargo-publish

on:
  release:
    types: [ created ]

jobs:
  cargo-publish:
    name: Cargo Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Rust
        run: |
          rustup update stable
          rustup default stable
          rustup -V
          rustc -Vv
          cargo -V
      - name: Publish to crates-io
        run: cargo publish --token  ${{ secrets.PUBLISH_KEY }} --verbose